branches:
  only:
    - release

language: java

jdk: openjdk11

services:
  - docker

install:
  - docker build -t dhavelock/segments-explorer:$TRAVIS_BUILD_NUMBER .
  - ./mvnw clean install

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push dhavelock/segments-explorer:$TRAVIS_BUILD_NUMBER
  on:
    branch: release